'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),core=require('../server/core.cjs');
const temporary=!process.env.NUAA_PROJECT,base=path.resolve('.dev');fs.mkdirSync(base,{recursive:true});const root=temporary?fs.mkdtempSync(path.join(base,'navigation ')):path.resolve(process.env.NUAA_PROJECT),main=path.join(root,'master.tex');
if(temporary){fs.mkdirSync(path.join(root,'template'));fs.mkdirSync(path.join(root,'bib'));fs.writeFileSync(main,String.raw`\documentclass{local}\renewcommand\nuaanotation[2]{#1#2}\makecover\makedeclare\makeabstract\nuaanotation{x}\optional[option]{x}\rpm\copied\argmax\bibliographystyle{bib/masterbib}\modernrows*[note]{rows.tex}\modernenv[Claim]{claim}\begin{claim}\end{claim}\begin{boxed}\end{boxed}\begin{fancy}\end{fancy}`);fs.writeFileSync(path.join(root,'local.cls'),String.raw`\InputIfFileExists{template/front.def}{}{}`);fs.writeFileSync(path.join(root,'template/front.def'),String.raw`% Public cover entry
\def\makecover{cover}
\newcommand\makedeclare{declare}
\newcommand\makeabstract{abstract}
\newcommand\nuaanotation[1]{#1}
\newcommand\optional[2][default]{#1#2}
\DeclareSIUnit{\rpm}{rpm}
\let\saved=\makecover
\NewCommandCopy{\copied}{\saved}
\DeclareMathOperator*{\argmax}{arg\,max}\NewDocumentCommand\modernrows{s O{default} m}{\innerrows{#3}}\newcommand\innerrows[1]{\input{#1}}\NewDocumentCommand\modernenv{O{Theorem} m}{\innerenv{#2}{#1}}\newcommand\innerenv[2]{\newtheorem{#1}{#2}}\newcommand\claim{same-name command}\newenvironment{boxed}[1]{#1}{}\renewenvironment{boxed}[2][default]{#1#2}{}\NewDocumentEnvironment{fancy}{O{choice} m}{#1#2}{}`);fs.writeFileSync(path.join(root,'rows.tex'),'Rows');fs.writeFileSync(path.join(root,'bib/masterbib.bst'),'ENTRY {} {} {}');}
const source=fs.readFileSync(main,'utf8'),original=fs.readFileSync(main);const child=spawn(process.execPath,[path.resolve('server/server.cjs')]);let buffer=Buffer.alloc(0),id=0;const pending=new Map();
function send(message){const data=Buffer.from(JSON.stringify({jsonrpc:'2.0',...message}));child.stdin.write('Content-Length: '+data.length+'\r\n\r\n');child.stdin.write(data);}
function request(method,params){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});send({id:n,method,params});});}
child.stdout.on('data',data=>{buffer=Buffer.concat([buffer,data]);while(true){const end=buffer.indexOf('\r\n\r\n');if(end<0)return;const size=Number(/Content-Length:\s*(\d+)/i.exec(buffer.subarray(0,end).toString())[1]);if(buffer.length<end+4+size)return;const m=JSON.parse(buffer.subarray(end+4,end+4+size));buffer=buffer.subarray(end+4+size);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}else if(m.id!==undefined)send({id:m.id,result:m.method==='workspace/configuration'?m.params.items.map(()=>({'latex.autoBuild.run':'never'})):null});}});
child.stderr.on('data',data=>process.stderr.write(data));const timer=setTimeout(()=>{child.kill();console.error('FAIL navigation timeout');process.exitCode=1;},30000);
(async()=>{try{
 await request('initialize',{rootUri:core.uri(root),capabilities:{textDocument:{completion:{completionItem:{snippetSupport:process.env.ENV_SNIPPETS==='1'}}}},initializationOptions:{'latex.autoBuild.run':'never'}});send({method:'initialized',params:{}});send({method:'textDocument/didOpen',params:{textDocument:{uri:core.uri(main),languageId:'latex',version:1,text:source}}});
 for(const name of ['makecover','makedeclare','makeabstract','nuaanotation',...(temporary?['optional','rpm','copied','argmax']:[])]){const start=source.lastIndexOf('\\'+name),position=core.position(source,start+3),textDocument={uri:core.uri(main)};assert(start>=0);const hover=await request('textDocument/hover',{textDocument,position});assert(hover?.contents.value.includes('\\'+name),name+' hover');assert(hover.contents.value.includes('定义：'));const defs=await request('textDocument/definition',{textDocument,position});assert(defs.length>=1,name+' definition');if(temporary&&name==='nuaanotation')assert.equal(defs.length,2);if(temporary&&name==='nuaanotation'){assert.equal(core.key(core.file(defs[0].uri)),core.key(main));assert(hover.contents.value.includes('{参数1}{参数2}'));}else assert(core.file(defs[0].uri).endsWith('.def'));}
 const hover=await request('textDocument/hover',{textDocument:{uri:core.uri(main)},position:core.position(source,source.indexOf('\\bibliographystyle')+5)});assert(hover.contents.value.includes('\\bibliographystyle{样式名或路径}'));
 const offset=source.indexOf('bib/masterbib'),defs=await request('textDocument/definition',{textDocument:{uri:core.uri(main)},position:core.position(source,offset+5)});assert.equal(core.key(core.file(defs[0].uri)),core.key(path.join(root,'bib/masterbib.bst')));


 if(temporary){const rowsAt=source.indexOf('rows.tex')+2,textDocument={uri:core.uri(main)};const targets=await request('textDocument/definition',{textDocument,position:core.position(source,rowsAt)});assert.equal(core.key(core.file(targets[0].uri)),core.key(path.join(root,'rows.tex')));const envAt=source.lastIndexOf('{claim}')+3,envTargets=await request('textDocument/definition',{textDocument,position:core.position(source,envAt)});assert.equal(core.offset(source,envTargets[0].range.start),source.indexOf('{claim}')+1);
 for(const [name,checks] of [['claim',['显示标题：Claim','生成命令：\\modernenv','注册：']],['boxed',['[参数1]{参数2}','默认值 default','定义：','存在 2 个静态定义候选']],['fancy',['[参数1]{参数2}','默认值 choice']]])for(const occurrence of ['\\begin{','\\end{']){const at=source.indexOf(occurrence+name)+occurrence.length+1,position=core.position(source,at),hover=await request('textDocument/hover',{textDocument,position});for(const check of checks)assert(hover.contents.value.includes(check),name+' '+check);assert.equal(source.slice(core.offset(source,hover.range.start),core.offset(source,hover.range.end)),name);}
 const boxedPosition=core.position(source,source.indexOf('\\begin{boxed}')+9),boxedDefs=await request('textDocument/definition',{textDocument,position:boxedPosition});assert.equal(boxedDefs.length,2);assert(boxedDefs[0].range.start.character>boxedDefs[1].range.start.character);
 const partial=source+'\n\\modernrows*[note]{ro';send({method:'textDocument/didChange',params:{textDocument:{uri:core.uri(main),version:2},contentChanges:[{text:partial}]}});const rowItems=await request('textDocument/completion',{textDocument,position:core.position(partial,partial.length)});assert(rowItems.some(item=>item.label==='rows'));
 for(const [suffix,expected] of [['\\begin{bo','expanded'],['\\begin{bo}','expanded'],['\\begin{bo}[keep]{content}','plain'],['\\begin{bo}\n[keep]{content}','plain'],['\\begin{bo}% note\n[keep]{content}','plain'],['\\end{bo}','plain']]){const content=source+'\n'+suffix,at=content.lastIndexOf('bo')+2;send({method:'textDocument/didChange',params:{textDocument:{uri:core.uri(main),version:3},contentChanges:[{text:content}]}});const items=await request('textDocument/completion',{textDocument,position:core.position(content,at)}),item=items.find(item=>item.label==='boxed');assert(item.documentation.value.includes('默认值 default'));assert(item.documentation.value.includes('存在 2 个静态定义候选'));assert.equal(item.detail,'\\begin{boxed}[参数1]{参数2}');if(process.env.ENV_SNIPPETS==='1'&&expected==='expanded'){assert.equal(item.insertTextFormat,2);assert.equal(item.textEdit.newText,'boxed}[${1:default}]{${2:参数2}}$0');assert.equal(core.offset(content,item.textEdit.range.end),at+(content[at]==='}'?1:0));}else{assert.equal(item.insertTextFormat,undefined);assert.equal(item.textEdit.newText,'boxed');assert.equal(core.offset(content,item.textEdit.range.end),at);}}
 const position=core.position(source,source.indexOf('\\copied')+3),hover=await request('textDocument/hover',{textDocument:{uri:core.uri(main)},position});assert(hover.contents.value.includes('\\copied → \\saved → \\makecover'));
  async function items(prefix){const text=source+'\n\\'+prefix;send({method:'textDocument/didChange',params:{textDocument:{uri:core.uri(main),version:2},contentChanges:[{text}]}});return request('textDocument/completion',{textDocument:{uri:core.uri(main)},position:core.position(text,text.length)});}
  const unit=(await items('rp')).find(item=>item.label==='\\rpm');assert(unit?.documentation.value.includes('单位内容：rpm'));
  const copy=(await items('cop')).find(item=>item.label==='\\copied');assert.equal(copy.insertText,'copied');assert(copy.documentation.value.includes('静态复制来源'));
  const front=path.join(root,'template/front.def'),text=fs.readFileSync(front,'utf8').replace(/\\DeclareSIUnit\{\\rpm\}\{rpm\}/,'').replace(/\\renewenvironment\{boxed\}\[2\]\[default\]\{#1#2\}\{\}/,'');send({method:'textDocument/didOpen',params:{textDocument:{uri:core.uri(front),languageId:'latex',version:1,text}}});assert(!(await items('rp')).some(item=>item.label==='\\rpm'),'Removed unit remained cached');const boxedHover=await request('textDocument/hover',{textDocument,position:boxedPosition});assert(!boxedHover.contents.value.includes('静态定义候选'));assert(!boxedHover.contents.value.includes('default'));assert.equal((await request('textDocument/definition',{textDocument,position:boxedPosition})).length,1);
 }

 else {const chapter=path.join(root,'content/chap5.tex'),text=fs.readFileSync(chapter,'utf8');send({method:'textDocument/didOpen',params:{textDocument:{uri:core.uri(chapter),languageId:'latex',version:1,text}}});const position=core.position(text,text.indexOf('\\rpm')+2),textDocument={uri:core.uri(chapter)},hover=await request('textDocument/hover',{textDocument,position});assert(hover.contents.value.includes('单位内容：rpm'));const defs=await request('textDocument/definition',{textDocument,position});assert.equal(core.key(core.file(defs[0].uri)),core.key(path.join(root,'config/preamble.tex')));assert.deepEqual(fs.readFileSync(chapter),Buffer.from(text));}

 if(!temporary){
  for(const [name,target] of [['nuaanotation','content/notation.tex'],['nuaaacronyms','content/acronyms.tex']]){const at=source.indexOf('\\'+name+'{')+name.length+2;assert(at>name.length+1);const defs=await request('textDocument/definition',{textDocument:{uri:core.uri(main)},position:core.position(source,at+3)});assert.equal(core.key(core.file(defs[0].uri)),core.key(path.join(root,target)));}
  const text=source+'\n\\nuaanotation{content/not';send({method:'textDocument/didChange',params:{textDocument:{uri:core.uri(main),version:10},contentChanges:[{text}]}});const items=await request('textDocument/completion',{textDocument:{uri:core.uri(main)},position:core.position(text,text.length)});assert(items.some(item=>item.label==='content/notation.tex'));
  const envText=source+'\n\\begin{definition}';send({method:'textDocument/didChange',params:{textDocument:{uri:core.uri(main),version:11},contentChanges:[{text:envText}]}});const defs=await request('textDocument/definition',{textDocument:{uri:core.uri(main)},position:core.position(envText,envText.length-4)});assert.equal(core.key(core.file(defs[0].uri)),core.key(path.join(root,'config/preamble.tex')));
  const envHover=await request('textDocument/hover',{textDocument:{uri:core.uri(main)},position:core.position(envText,envText.length-4)});assert(envHover.contents.value.includes('显示标题：定义'));assert(envHover.contents.value.includes('生成命令：\\nuaatheoremchapu'));
  const partial=source+'\n\\begin{ass';send({method:'textDocument/didChange',params:{textDocument:{uri:core.uri(main),version:12},contentChanges:[{text:partial}]}});const envItems=await request('textDocument/completion',{textDocument:{uri:core.uri(main)},position:core.position(partial,partial.length)});assert(envItems.some(item=>item.label==='assumption'));
 }
 assert.deepEqual(fs.readFileSync(main),original);console.log('PASS navigation LSP: class-loaded module commands hover/jump at call sites, bibliography signature and local BST path; project files unchanged');
 await request('shutdown',null);send({method:'exit',params:null});
 }catch(error){console.error(error);process.exitCode=1;}finally{clearTimeout(timer);child.kill();if(temporary){assert(path.resolve(root).startsWith(base+path.sep));fs.rmSync(root,{recursive:true,force:true});}}})();
