'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),core=require('../server/core.cjs'),resolver=require('../server/paths.cjs'),completion=require('../server/completion.cjs'),packages=require('../server/package-data.cjs');
const temp=path.resolve('.dev');fs.mkdirSync(temp,{recursive:true});const root=fs.mkdtempSync(path.join(temp,'path-probe ')),main=path.join(root,'main.tex');
function write(name,text=''){const file=path.join(root,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);return file;}
try{
 write('main.tex',String.raw`\documentclass{localclass}\graphicspath{{figures/}{logos/}}\import{parts/}{one}\import{other/}{one}\input{ordinary}\bibliographystyle{bib/local}`);
 write('localclass.cls',String.raw`\InputIfFileExists{modules/cover.def}{}{}\RequirePackageWithOptions{nested/localstyle}`);write('modules/cover.def',String.raw`\def\makecover{cover}`);write('nested/localstyle.sty',String.raw`\newcommand{\localmacro}[1]{#1}`);
 const child=write('parts/one.tex',String.raw`\subimport{sub/}{two}\includegraphics{diagram}\input{shared}`);write('parts/sub/two.tex',String.raw`\input{leaf}\import{absolute/}{reset}`);const leaf=write('parts/sub/leaf.tex');write('absolute/reset.tex');write('parts/shared.tex');write('shared.tex');write('ordinary.tex');write('figures/diagram.pdf');write('logos/diagram.pdf');const localImage=write('parts/diagram.pdf');write('other/one.tex',String.raw`\input{shared}`);write('other/shared.tex');write('bib/local.bst');
 const files=core.dependencies(main),idx=core.index([...files]);assert(files.has(core.key(leaf)));assert(idx.commands.has('makecover'));assert(idx.commands.has('localmacro'));assert(!files.has(core.key(path.join(root,'bib/local.bst'))));assert.equal(core.key(core.rootFile(child,[root])),core.key(main));
 const text=fs.readFileSync(child,'utf8');assert.deepEqual(resolver.resolve(child,main,'input','shared').map(core.key),[core.key(path.join(root,'parts/shared.tex'))]);assert.deepEqual(resolver.resolve(child,main,'includegraphics','diagram').map(core.key),[core.key(localImage)]);
 const ordinary=path.join(root,'ordinary.tex');assert.deepEqual(resolver.resolve(ordinary,main,'includegraphics','diagram').map(core.key),[core.key(path.join(root,'figures/diagram.pdf'))]);
 const usage=String.raw`\bibliographystyle{bib/local}`,style=completion.pathDefinition(usage,core.position(usage,usage.indexOf('local')+2),main,main);assert.equal(core.key(core.file(style[0].uri)),core.key(path.join(root,'bib/local.bst')));
 const partial=String.raw`\subimport{sub/}{tw}`,pos=core.position(partial,partial.indexOf('tw')+2),context=completion.context(partial,pos);assert.equal(context.directory,'sub/');const item=completion.paths(child,main,context.command,context.prefix,null,context).find(item=>item.label==='two');assert(item);assert.equal(core.key(item.target),core.key(path.join(root,'parts/sub/two.tex')));
 const directory=completion.context(String.raw`\subimport{su`,{line:0,character:13});assert(directory.directoryOnly);assert(completion.paths(child,main,directory.command,directory.prefix,null,directory).every(item=>item.label.endsWith('/')));
 // One file imported from two paths has two real contexts; return both instead of choosing arbitrarily.
 write('common.tex',String.raw`\input{shared}`);write('main.tex',String.raw`\documentclass{localclass}\import{parts/}{../common}\import{other/}{../common}`);assert.equal(resolver.resolve(path.join(root,'common.tex'),main,'input','shared').length,2);
 const docs=new Map([[core.key(main),{text:String.raw`\documentclass{localclass}\graphicspath{{logos/}}\input{ordinary}`}]]);assert.equal(core.key(resolver.resolve(ordinary,main,'includegraphics','diagram',docs)[0]),core.key(path.join(root,'logos/diagram.pdf')));
 // An unrelated package with the same basename must not contribute definitions.
 write('wrong/localstyle.sty',String.raw`\newcommand{\wrong}{wrong}`);const catalog=packages.context([...core.dependencies(main,docs)],[root],docs);assert(!catalog.localFiles.some(file=>core.key(file)===core.key(path.join(root,'wrong/localstyle.sty'))));
 assert.equal(resolver.resolve(main,main,'input',String.raw`\dynamic`).length,0);
 console.log('PASS paths: imports/reset/nested contexts, class modules, graphics inheritance, exact BST links, directory completion, unsaved changes, ambiguity and local package isolation');
}finally{const resolved=path.resolve(root);assert(resolved.startsWith(temp+path.sep));fs.rmSync(resolved,{recursive:true,force:true});}
