/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_FUNCTION = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_string = 5,
  sym_number = 6,
  anon_sym_SQUOTE = 7,
  anon_sym_ENTRY = 8,
  anon_sym_INTEGERS = 9,
  anon_sym_STRINGS = 10,
  anon_sym_MACRO = 11,
  anon_sym_READ = 12,
  anon_sym_EXECUTE = 13,
  anon_sym_ITERATE = 14,
  anon_sym_REVERSE = 15,
  anon_sym_SORT = 16,
  sym_comment = 17,
  sym_program = 18,
  sym__value = 19,
  sym_function_definition = 20,
  sym_block = 21,
  sym_quoted_identifier = 22,
  sym_keyword = 23,
  aux_sym_program_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_FUNCTION] = "FUNCTION",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_ENTRY] = "ENTRY",
  [anon_sym_INTEGERS] = "INTEGERS",
  [anon_sym_STRINGS] = "STRINGS",
  [anon_sym_MACRO] = "MACRO",
  [anon_sym_READ] = "READ",
  [anon_sym_EXECUTE] = "EXECUTE",
  [anon_sym_ITERATE] = "ITERATE",
  [anon_sym_REVERSE] = "REVERSE",
  [anon_sym_SORT] = "SORT",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym__value] = "_value",
  [sym_function_definition] = "function_definition",
  [sym_block] = "block",
  [sym_quoted_identifier] = "quoted_identifier",
  [sym_keyword] = "keyword",
  [aux_sym_program_repeat1] = "program_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_FUNCTION] = anon_sym_FUNCTION,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_ENTRY] = anon_sym_ENTRY,
  [anon_sym_INTEGERS] = anon_sym_INTEGERS,
  [anon_sym_STRINGS] = anon_sym_STRINGS,
  [anon_sym_MACRO] = anon_sym_MACRO,
  [anon_sym_READ] = anon_sym_READ,
  [anon_sym_EXECUTE] = anon_sym_EXECUTE,
  [anon_sym_ITERATE] = anon_sym_ITERATE,
  [anon_sym_REVERSE] = anon_sym_REVERSE,
  [anon_sym_SORT] = anon_sym_SORT,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym__value] = sym__value,
  [sym_function_definition] = sym_function_definition,
  [sym_block] = sym_block,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [sym_keyword] = sym_keyword,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_FUNCTION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ENTRY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INTEGERS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STRINGS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MACRO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_READ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EXECUTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ITERATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REVERSE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SORT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 4},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 3,
  [8] = 2,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 11,
  [15] = 10,
  [16] = 16,
  [17] = 16,
  [18] = 12,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 24,
  [27] = 25,
  [28] = 22,
  [29] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '%') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'E') ADVANCE(1);
      if (lookahead == 'F') ADVANCE(2);
      if (lookahead == 'I') ADVANCE(3);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'R') ADVANCE(5);
      if (lookahead == 'S') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'N') ADVANCE(7);
      if (lookahead == 'X') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'U') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'N') ADVANCE(10);
      if (lookahead == 'T') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'O') ADVANCE(14);
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'N') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'C') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(22);
      if (lookahead == 'V') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'R') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'C') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'R') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'R') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'D') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'T') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'I') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'Y') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'U') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'G') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'A') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'O') ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_READ);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(42);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SORT);
      END_STATE();
    case 35:
      if (lookahead == 'N') ADVANCE(43);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_ENTRY);
      END_STATE();
    case 37:
      if (lookahead == 'T') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'I') ADVANCE(45);
      END_STATE();
    case 39:
      if (lookahead == 'E') ADVANCE(46);
      END_STATE();
    case 40:
      if (lookahead == 'T') ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_MACRO);
      END_STATE();
    case 42:
      if (lookahead == 'S') ADVANCE(48);
      END_STATE();
    case 43:
      if (lookahead == 'G') ADVANCE(49);
      END_STATE();
    case 44:
      if (lookahead == 'E') ADVANCE(50);
      END_STATE();
    case 45:
      if (lookahead == 'O') ADVANCE(51);
      END_STATE();
    case 46:
      if (lookahead == 'R') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'E') ADVANCE(53);
      END_STATE();
    case 48:
      if (lookahead == 'E') ADVANCE(54);
      END_STATE();
    case 49:
      if (lookahead == 'S') ADVANCE(55);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EXECUTE);
      END_STATE();
    case 51:
      if (lookahead == 'N') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == 'S') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_ITERATE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_REVERSE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_STRINGS);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_FUNCTION);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_INTEGERS);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_FUNCTION] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_ENTRY] = ACTIONS(1),
    [anon_sym_INTEGERS] = ACTIONS(1),
    [anon_sym_STRINGS] = ACTIONS(1),
    [anon_sym_MACRO] = ACTIONS(1),
    [anon_sym_READ] = ACTIONS(1),
    [anon_sym_EXECUTE] = ACTIONS(1),
    [anon_sym_ITERATE] = ACTIONS(1),
    [anon_sym_REVERSE] = ACTIONS(1),
    [anon_sym_SORT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_program] = STATE(23),
    [sym__value] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_block] = STATE(4),
    [sym_quoted_identifier] = STATE(4),
    [sym_keyword] = STATE(4),
    [aux_sym_program_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_FUNCTION] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_string] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_ENTRY] = ACTIONS(17),
    [anon_sym_INTEGERS] = ACTIONS(17),
    [anon_sym_STRINGS] = ACTIONS(17),
    [anon_sym_MACRO] = ACTIONS(17),
    [anon_sym_READ] = ACTIONS(17),
    [anon_sym_EXECUTE] = ACTIONS(17),
    [anon_sym_ITERATE] = ACTIONS(17),
    [anon_sym_REVERSE] = ACTIONS(17),
    [anon_sym_SORT] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_block] = STATE(3),
    [sym_quoted_identifier] = STATE(3),
    [sym_keyword] = STATE(3),
    [aux_sym_program_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_FUNCTION] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_string] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_ENTRY] = ACTIONS(31),
    [anon_sym_INTEGERS] = ACTIONS(31),
    [anon_sym_STRINGS] = ACTIONS(31),
    [anon_sym_MACRO] = ACTIONS(31),
    [anon_sym_READ] = ACTIONS(31),
    [anon_sym_EXECUTE] = ACTIONS(31),
    [anon_sym_ITERATE] = ACTIONS(31),
    [anon_sym_REVERSE] = ACTIONS(31),
    [anon_sym_SORT] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__value] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_block] = STATE(6),
    [sym_quoted_identifier] = STATE(6),
    [sym_keyword] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_FUNCTION] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(35),
    [sym_string] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_ENTRY] = ACTIONS(31),
    [anon_sym_INTEGERS] = ACTIONS(31),
    [anon_sym_STRINGS] = ACTIONS(31),
    [anon_sym_MACRO] = ACTIONS(31),
    [anon_sym_READ] = ACTIONS(31),
    [anon_sym_EXECUTE] = ACTIONS(31),
    [anon_sym_ITERATE] = ACTIONS(31),
    [anon_sym_REVERSE] = ACTIONS(31),
    [anon_sym_SORT] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__value] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym_block] = STATE(5),
    [sym_quoted_identifier] = STATE(5),
    [sym_keyword] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(41),
    [anon_sym_FUNCTION] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_string] = ACTIONS(43),
    [sym_number] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_ENTRY] = ACTIONS(17),
    [anon_sym_INTEGERS] = ACTIONS(17),
    [anon_sym_STRINGS] = ACTIONS(17),
    [anon_sym_MACRO] = ACTIONS(17),
    [anon_sym_READ] = ACTIONS(17),
    [anon_sym_EXECUTE] = ACTIONS(17),
    [anon_sym_ITERATE] = ACTIONS(17),
    [anon_sym_REVERSE] = ACTIONS(17),
    [anon_sym_SORT] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__value] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym_block] = STATE(5),
    [sym_quoted_identifier] = STATE(5),
    [sym_keyword] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_FUNCTION] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(53),
    [sym_string] = ACTIONS(56),
    [sym_number] = ACTIONS(56),
    [anon_sym_SQUOTE] = ACTIONS(59),
    [anon_sym_ENTRY] = ACTIONS(62),
    [anon_sym_INTEGERS] = ACTIONS(62),
    [anon_sym_STRINGS] = ACTIONS(62),
    [anon_sym_MACRO] = ACTIONS(62),
    [anon_sym_READ] = ACTIONS(62),
    [anon_sym_EXECUTE] = ACTIONS(62),
    [anon_sym_ITERATE] = ACTIONS(62),
    [anon_sym_REVERSE] = ACTIONS(62),
    [anon_sym_SORT] = ACTIONS(62),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__value] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_block] = STATE(6),
    [sym_quoted_identifier] = STATE(6),
    [sym_keyword] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_FUNCTION] = ACTIONS(68),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_string] = ACTIONS(74),
    [sym_number] = ACTIONS(74),
    [anon_sym_SQUOTE] = ACTIONS(77),
    [anon_sym_ENTRY] = ACTIONS(80),
    [anon_sym_INTEGERS] = ACTIONS(80),
    [anon_sym_STRINGS] = ACTIONS(80),
    [anon_sym_MACRO] = ACTIONS(80),
    [anon_sym_READ] = ACTIONS(80),
    [anon_sym_EXECUTE] = ACTIONS(80),
    [anon_sym_ITERATE] = ACTIONS(80),
    [anon_sym_REVERSE] = ACTIONS(80),
    [anon_sym_SORT] = ACTIONS(80),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__value] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_block] = STATE(6),
    [sym_quoted_identifier] = STATE(6),
    [sym_keyword] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_FUNCTION] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(83),
    [sym_string] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_ENTRY] = ACTIONS(31),
    [anon_sym_INTEGERS] = ACTIONS(31),
    [anon_sym_STRINGS] = ACTIONS(31),
    [anon_sym_MACRO] = ACTIONS(31),
    [anon_sym_READ] = ACTIONS(31),
    [anon_sym_EXECUTE] = ACTIONS(31),
    [anon_sym_ITERATE] = ACTIONS(31),
    [anon_sym_REVERSE] = ACTIONS(31),
    [anon_sym_SORT] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__value] = STATE(7),
    [sym_function_definition] = STATE(7),
    [sym_block] = STATE(7),
    [sym_quoted_identifier] = STATE(7),
    [sym_keyword] = STATE(7),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(85),
    [anon_sym_FUNCTION] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(87),
    [sym_string] = ACTIONS(89),
    [sym_number] = ACTIONS(89),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_ENTRY] = ACTIONS(31),
    [anon_sym_INTEGERS] = ACTIONS(31),
    [anon_sym_STRINGS] = ACTIONS(31),
    [anon_sym_MACRO] = ACTIONS(31),
    [anon_sym_READ] = ACTIONS(31),
    [anon_sym_EXECUTE] = ACTIONS(31),
    [anon_sym_ITERATE] = ACTIONS(31),
    [anon_sym_REVERSE] = ACTIONS(31),
    [anon_sym_SORT] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(91),
    [sym_identifier] = ACTIONS(93),
    [anon_sym_FUNCTION] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(91),
    [sym_string] = ACTIONS(91),
    [sym_number] = ACTIONS(91),
    [anon_sym_SQUOTE] = ACTIONS(91),
    [anon_sym_ENTRY] = ACTIONS(93),
    [anon_sym_INTEGERS] = ACTIONS(93),
    [anon_sym_STRINGS] = ACTIONS(93),
    [anon_sym_MACRO] = ACTIONS(93),
    [anon_sym_READ] = ACTIONS(93),
    [anon_sym_EXECUTE] = ACTIONS(93),
    [anon_sym_ITERATE] = ACTIONS(93),
    [anon_sym_REVERSE] = ACTIONS(93),
    [anon_sym_SORT] = ACTIONS(93),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(95),
    [sym_identifier] = ACTIONS(97),
    [anon_sym_FUNCTION] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(95),
    [sym_string] = ACTIONS(95),
    [sym_number] = ACTIONS(95),
    [anon_sym_SQUOTE] = ACTIONS(95),
    [anon_sym_ENTRY] = ACTIONS(97),
    [anon_sym_INTEGERS] = ACTIONS(97),
    [anon_sym_STRINGS] = ACTIONS(97),
    [anon_sym_MACRO] = ACTIONS(97),
    [anon_sym_READ] = ACTIONS(97),
    [anon_sym_EXECUTE] = ACTIONS(97),
    [anon_sym_ITERATE] = ACTIONS(97),
    [anon_sym_REVERSE] = ACTIONS(97),
    [anon_sym_SORT] = ACTIONS(97),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(99),
    [sym_identifier] = ACTIONS(101),
    [anon_sym_FUNCTION] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(99),
    [sym_string] = ACTIONS(99),
    [sym_number] = ACTIONS(99),
    [anon_sym_SQUOTE] = ACTIONS(99),
    [anon_sym_ENTRY] = ACTIONS(101),
    [anon_sym_INTEGERS] = ACTIONS(101),
    [anon_sym_STRINGS] = ACTIONS(101),
    [anon_sym_MACRO] = ACTIONS(101),
    [anon_sym_READ] = ACTIONS(101),
    [anon_sym_EXECUTE] = ACTIONS(101),
    [anon_sym_ITERATE] = ACTIONS(101),
    [anon_sym_REVERSE] = ACTIONS(101),
    [anon_sym_SORT] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(103),
    [sym_identifier] = ACTIONS(105),
    [anon_sym_FUNCTION] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(103),
    [sym_string] = ACTIONS(103),
    [sym_number] = ACTIONS(103),
    [anon_sym_SQUOTE] = ACTIONS(103),
    [anon_sym_ENTRY] = ACTIONS(105),
    [anon_sym_INTEGERS] = ACTIONS(105),
    [anon_sym_STRINGS] = ACTIONS(105),
    [anon_sym_MACRO] = ACTIONS(105),
    [anon_sym_READ] = ACTIONS(105),
    [anon_sym_EXECUTE] = ACTIONS(105),
    [anon_sym_ITERATE] = ACTIONS(105),
    [anon_sym_REVERSE] = ACTIONS(105),
    [anon_sym_SORT] = ACTIONS(105),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [sym_identifier] = ACTIONS(93),
    [anon_sym_FUNCTION] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(91),
    [anon_sym_RBRACE] = ACTIONS(91),
    [sym_string] = ACTIONS(91),
    [sym_number] = ACTIONS(91),
    [anon_sym_SQUOTE] = ACTIONS(91),
    [anon_sym_ENTRY] = ACTIONS(93),
    [anon_sym_INTEGERS] = ACTIONS(93),
    [anon_sym_STRINGS] = ACTIONS(93),
    [anon_sym_MACRO] = ACTIONS(93),
    [anon_sym_READ] = ACTIONS(93),
    [anon_sym_EXECUTE] = ACTIONS(93),
    [anon_sym_ITERATE] = ACTIONS(93),
    [anon_sym_REVERSE] = ACTIONS(93),
    [anon_sym_SORT] = ACTIONS(93),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [sym_identifier] = ACTIONS(101),
    [anon_sym_FUNCTION] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(99),
    [anon_sym_RBRACE] = ACTIONS(99),
    [sym_string] = ACTIONS(99),
    [sym_number] = ACTIONS(99),
    [anon_sym_SQUOTE] = ACTIONS(99),
    [anon_sym_ENTRY] = ACTIONS(101),
    [anon_sym_INTEGERS] = ACTIONS(101),
    [anon_sym_STRINGS] = ACTIONS(101),
    [anon_sym_MACRO] = ACTIONS(101),
    [anon_sym_READ] = ACTIONS(101),
    [anon_sym_EXECUTE] = ACTIONS(101),
    [anon_sym_ITERATE] = ACTIONS(101),
    [anon_sym_REVERSE] = ACTIONS(101),
    [anon_sym_SORT] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [sym_identifier] = ACTIONS(97),
    [anon_sym_FUNCTION] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(95),
    [anon_sym_RBRACE] = ACTIONS(95),
    [sym_string] = ACTIONS(95),
    [sym_number] = ACTIONS(95),
    [anon_sym_SQUOTE] = ACTIONS(95),
    [anon_sym_ENTRY] = ACTIONS(97),
    [anon_sym_INTEGERS] = ACTIONS(97),
    [anon_sym_STRINGS] = ACTIONS(97),
    [anon_sym_MACRO] = ACTIONS(97),
    [anon_sym_READ] = ACTIONS(97),
    [anon_sym_EXECUTE] = ACTIONS(97),
    [anon_sym_ITERATE] = ACTIONS(97),
    [anon_sym_REVERSE] = ACTIONS(97),
    [anon_sym_SORT] = ACTIONS(97),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym_identifier] = ACTIONS(109),
    [anon_sym_FUNCTION] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [sym_number] = ACTIONS(107),
    [anon_sym_SQUOTE] = ACTIONS(107),
    [anon_sym_ENTRY] = ACTIONS(109),
    [anon_sym_INTEGERS] = ACTIONS(109),
    [anon_sym_STRINGS] = ACTIONS(109),
    [anon_sym_MACRO] = ACTIONS(109),
    [anon_sym_READ] = ACTIONS(109),
    [anon_sym_EXECUTE] = ACTIONS(109),
    [anon_sym_ITERATE] = ACTIONS(109),
    [anon_sym_REVERSE] = ACTIONS(109),
    [anon_sym_SORT] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [sym_identifier] = ACTIONS(109),
    [anon_sym_FUNCTION] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(107),
    [anon_sym_RBRACE] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [sym_number] = ACTIONS(107),
    [anon_sym_SQUOTE] = ACTIONS(107),
    [anon_sym_ENTRY] = ACTIONS(109),
    [anon_sym_INTEGERS] = ACTIONS(109),
    [anon_sym_STRINGS] = ACTIONS(109),
    [anon_sym_MACRO] = ACTIONS(109),
    [anon_sym_READ] = ACTIONS(109),
    [anon_sym_EXECUTE] = ACTIONS(109),
    [anon_sym_ITERATE] = ACTIONS(109),
    [anon_sym_REVERSE] = ACTIONS(109),
    [anon_sym_SORT] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [sym_identifier] = ACTIONS(105),
    [anon_sym_FUNCTION] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [sym_string] = ACTIONS(103),
    [sym_number] = ACTIONS(103),
    [anon_sym_SQUOTE] = ACTIONS(103),
    [anon_sym_ENTRY] = ACTIONS(105),
    [anon_sym_INTEGERS] = ACTIONS(105),
    [anon_sym_STRINGS] = ACTIONS(105),
    [anon_sym_MACRO] = ACTIONS(105),
    [anon_sym_READ] = ACTIONS(105),
    [anon_sym_EXECUTE] = ACTIONS(105),
    [anon_sym_ITERATE] = ACTIONS(105),
    [anon_sym_REVERSE] = ACTIONS(105),
    [anon_sym_SORT] = ACTIONS(105),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_block,
  [10] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
  [20] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
  [27] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_identifier,
  [34] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [41] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identifier,
  [48] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
  [55] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_identifier,
  [62] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
  [69] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_identifier,
  [76] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 10,
  [SMALL_STATE(21)] = 20,
  [SMALL_STATE(22)] = 27,
  [SMALL_STATE(23)] = 34,
  [SMALL_STATE(24)] = 41,
  [SMALL_STATE(25)] = 48,
  [SMALL_STATE(26)] = 55,
  [SMALL_STATE(27)] = 62,
  [SMALL_STATE(28)] = 69,
  [SMALL_STATE(29)] = 76,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_identifier, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_identifier, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bibtex_style(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bibtex_style",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
